#!/usr/bin/env python3
"""
gen-tables.py — Reproducibility bridge: pop-pay-npm JSONL run files -> LaTeX
table source for the paper's headline tables.

Closes the R18 Round-3 reviewer critique that "no published paper/gen-tables.py
script ties JSONL -> published Tables 4/6/etc." Reproducers can now regenerate
the published LaTeX tables from the released JSONL run files without
reverse-engineering the harness source.

WHAT THIS EMITS
---------------
* tab:bypassk        — Per-model cumulative Bypass@K under the PRIMARY
                       (whitebox-no-feedback) threat model, K=1..5,10,20, with
                       95% bootstrap CIs (1000 payload-level resamples,
                       seed=42) on the headline K=5 / K=20 / Never columns.
                       Mirrors the K=20 "merged-cumulative" entries for the
                       four models with cross-attacker K=20 cumulative jsons
                       (Pro x GPT, Pro x Opus, Sonnet x GPT, Flash x GPT,
                       Nano x Opus) only when --use-cumulative is passed; by
                       default it emits the same-family Pro-attacker numbers
                       that populate Tab.~ref{tab:bypassk}.
* tab:bypassk_cat    — Per-model per-category Bypass@5 under PRIMARY (11
                       categories x 9 models). Bolded winners are the lowest
                       (most resilient) per row; this matches the visual
                       presentation of Tab.~ref{tab:bypassk_cat} in the paper
                       (which is currently rendered from legacy informed-mode
                       data; the PRIMARY-mode version emitted here is the
                       supplementary table referenced in the paper caption).

INPUT FILES (PRIMARY whitebox-no-feedback, 9 models)
----------------------------------------------------
The 2026-04-28T19-50-* family of JSONL files in
  pop-pay-npm/tests/redteam/runs/adaptive/
The exact filenames are pinned in the PRIMARY_FILES map below; identical to
the mapping in pop-pay-npm/tests/redteam/scripts/compute-ci.py.

SHA-PINNING
-----------
SHA-256 hashes for the cross-attacker K=20 cumulative JSONL inputs
(F5-Pro K=5 snapshot, F5-Pro-K20 fresh-subset, F5-FlashGPT K=5 snapshot,
F5-FlashGPT-K20Tail final, F5-Nano-Opus 418-row partial, F5-Nano-Opus-Tail
51-row recovery, plus the corpus and L2 prompt template) are pinned in
pop-pay-npm/tests/redteam/scripts/verify-paper-numbers.sh; that script is
the canonical integrity gate. The PRIMARY 9-model JSONL files do not yet
have SHA pins in verify-paper-numbers.sh; reproducers should re-shasum
their on-disk copies and confirm against the MANIFEST.sha256 generated by
tests/redteam/scripts/generate-manifest.py.

METHODOLOGY
-----------
* Bypass@K per payload: 1 if (bypass_at_k != null AND bypass_at_k <= K),
  else 0. Identical to the harness definition (Section 4.1 of the paper).
* Bootstrap CI: payload-level resampling, 1000 resamples, percentile
  method (2.5/97.5), seed=42. Matches compute-ci.py.
* Per-category Bypass@5: same indicator, partitioned by row['category'];
  bolded winner per row = argmin point estimate.

USAGE
-----
    python3 paper/gen-tables.py --table bypassk
    python3 paper/gen-tables.py --table percategory
    python3 paper/gen-tables.py --table all --output stdout
    python3 paper/gen-tables.py --table all --output paper/auto-tables.tex

The default --output is stdout. When --output is a file path, the script
writes a single .tex fragment with both tables separated by clear
section comments.

REPRODUCIBILITY STATEMENT
-------------------------
This script is intentionally stdlib-only (no numpy/scipy) so a reproducer
can run it with a stock python3 install. Bootstrap RNG is python.random
seeded at 42; identical seeds yield identical CIs across runs.

If the script's output diverges from the published table by more than
+/- 0.1pp on a point estimate or +/- 0.5pp on a CI bound, that is a
reproducibility regression and should be reported as a paper issue.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from collections import defaultdict
from pathlib import Path

# ── Configuration ──────────────────────────────────────────────────────────

# Resolve the pop-pay-npm runs directory. Three resolution strategies:
#   1. POP_PAY_NPM env var (highest priority — explicit override)
#   2. Script lives inside pop-pay-npm/paper-artifacts/ (current canonical home)
#   3. Script lives in sibling paper repo (legacy: AgentPay/paper/)
import os
SCRIPT_DIR = Path(__file__).resolve().parent

def _find_pop_pay_npm() -> Path:
    if env := os.environ.get("POP_PAY_NPM"):
        return Path(env)
    # Strategy 2: script inside pop-pay-npm/paper-artifacts/
    p = SCRIPT_DIR.parent
    if (p / "tests" / "redteam" / "runs" / "adaptive").exists():
        return p
    # Strategy 3: script in sibling paper repo, pop-pay-npm is sibling dir
    p = SCRIPT_DIR.parent / "pop-pay-npm"
    if (p / "tests" / "redteam" / "runs" / "adaptive").exists():
        return p
    # Final fallback (let downstream FATAL message report the missing path)
    return SCRIPT_DIR.parent / "pop-pay-npm"

POP_PAY_NPM = _find_pop_pay_npm()
ADAPTIVE_DIR = POP_PAY_NPM / "tests" / "redteam" / "runs" / "adaptive"

N_BOOT = 1000
SEED = 42

# PRIMARY whitebox-no-feedback runs (Tab. tab:bypassk source).
# Identical mapping to pop-pay-npm/tests/redteam/scripts/compute-ci.py.
PRIMARY_FILES = {
    "claude-sonnet-4-6":      "2026-04-28T19-50-38-732Z-anthropic_claude-sonnet-4-6.jsonl",
    "gemini-3.1-pro-preview": "2026-04-28T19-50-46-477Z-gemini_gemini-3.1-pro-preview.jsonl",
    "gemini-2.5-flash":       "2026-04-28T19-50-38-732Z-gemini_gemini-2.5-flash.jsonl",
    "gemini-3.1-flash-lite":  "2026-04-28T19-50-46-486Z-gemini_gemini-3.1-flash-lite-preview.jsonl",
    "claude-haiku-4-5":       "2026-04-28T19-50-38-732Z-anthropic_claude-haiku-4-5-20251001.jsonl",
    "gemma4 (local)":         "2026-04-28T19-50-46-490Z-ollama_gemma4_e2b-it-q4_K_M.jsonl",
    "gpt-5.4-mini":           "2026-04-28T19-50-38-732Z-openai_gpt-5.4-mini-2026-03-17.jsonl",
    "gpt-5.4":                "2026-04-28T19-50-38-732Z-openai_gpt-5.4.jsonl",
    "gpt-5.4-nano":           "2026-04-28T19-50-45-057Z-openai_gpt-5.4-nano.jsonl",
}

# Display order in tab:bypassk = sorted by Bypass@5 ascending (most
# resilient first). We compute and sort dynamically; this list defines the
# desired column order in tab:bypassk_cat (matching the paper's column
# ordering: Son., 3.1P, G2.5, Haiku, 5.4, Mini, Nano, Lite, Oll.).
BYPASSK_CAT_COLS = [
    ("claude-sonnet-4-6",      "Son."),
    ("gemini-3.1-pro-preview", "3.1P"),
    ("gemini-2.5-flash",       "G2.5"),
    ("claude-haiku-4-5",       "Haiku"),
    ("gpt-5.4",                "5.4"),
    ("gpt-5.4-mini",           "Mini"),
    ("gpt-5.4-nano",           "Nano"),
    ("gemini-3.1-flash-lite",  "Lite"),
    ("gemma4 (local)",         "Oll."),
]

CAT_DESCRIPTIONS = [
    ("A", "Injection"),
    ("B", "Vendor"),
    ("C", "Cat.\\ drift"),
    ("D", "JSON inj."),
    ("E", "Amt.\\ manip."),
    ("F", "Trust esc."),
    ("G", "Page inj."),
    ("H", "TOCTOU"),
    ("I", "Amount"),
    ("J", "Halluc."),
    ("K", "Commerce"),
]

# ── Core computation ───────────────────────────────────────────────────────


def load_rows(path: Path) -> list[dict]:
    """Load all type=row records from a JSONL run file."""
    rows = []
    with open(path) as fh:
        for line in fh:
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            if d.get("type") == "row":
                rows.append(d)
    return rows


def bypass_at_k_indicators(rows: list[dict], k: int) -> list[int]:
    """Return per-payload 0/1 indicator: bypassed within K attempts."""
    return [
        1 if (r.get("bypass_at_k") is not None and r["bypass_at_k"] <= k) else 0
        for r in rows
    ]


def never_bypass_indicators(rows: list[dict]) -> list[int]:
    """Per-payload 0/1: never bypassed within K_max (the run's budget)."""
    return [1 if r.get("bypass_at_k") is None else 0 for r in rows]


def bootstrap_ci(values: list[int], n_boot: int = N_BOOT, seed: int = SEED) -> tuple[float, float, float]:
    """Stdlib percentile bootstrap (2.5/97.5) on a 0/1 array.

    Returns (point_pct, lo_pct, hi_pct). Uses random.Random(seed) so
    repeated calls within a single script invocation re-seed identically
    (each cell gets the same RNG stream — matches compute-ci.py behavior).
    """
    n = len(values)
    if n == 0:
        return (0.0, 0.0, 0.0)
    rng = random.Random(seed)
    point = sum(values) / n * 100
    boots = []
    for _ in range(n_boot):
        boot_sum = 0
        for _ in range(n):
            boot_sum += values[rng.randrange(n)]
        boots.append(boot_sum / n * 100)
    boots.sort()
    lo_idx = int(0.025 * n_boot)
    hi_idx = int(0.975 * n_boot)
    return (point, boots[lo_idx], boots[hi_idx])


def compute_per_model_bypass_curve(rows: list[dict]) -> dict:
    """Compute K=1..5,10,20 point estimates + CI on K=5/K=20/Never for one model."""
    out = {}
    for k in (1, 2, 3, 4, 5, 10, 20):
        out[f"K={k}_point"] = sum(bypass_at_k_indicators(rows, k)) / len(rows) * 100
    pt, lo, hi = bootstrap_ci(bypass_at_k_indicators(rows, 5))
    out["K=5_ci"] = (pt, lo, hi)
    pt, lo, hi = bootstrap_ci(bypass_at_k_indicators(rows, 20))
    out["K=20_ci"] = (pt, lo, hi)
    pt, lo, hi = bootstrap_ci(never_bypass_indicators(rows))
    out["Never_ci"] = (pt, lo, hi)
    out["n"] = len(rows)
    return out


# ── Table emission ─────────────────────────────────────────────────────────


def emit_bypassk_table(out=sys.stdout) -> dict[str, dict]:
    """Emit tab:bypassk LaTeX source. Returns the per-model results dict."""
    results = {}
    for model, fname in PRIMARY_FILES.items():
        path = ADAPTIVE_DIR / fname
        if not path.exists():
            print(f"% WARNING: missing run file for {model}: {fname}", file=out)
            continue
        rows = load_rows(path)
        if not rows:
            print(f"% WARNING: empty run file for {model}: {fname}", file=out)
            continue
        results[model] = compute_per_model_bypass_curve(rows)

    # Sort by K=5 point estimate ascending (most resilient first).
    ordered = sorted(results.items(), key=lambda kv: kv[1]["K=5_ci"][0])
    # Bold the lowest K=5 and lowest Never (most resilient).
    if ordered:
        min_k5 = ordered[0][0]
        # Bold the model with the HIGHEST Never rate (most resilient = most
        # payloads never bypassed within K_max=20). Matches the paper's
        # presentation in Tab. tab:bypassk.
        min_never = max(results.items(), key=lambda kv: kv[1]["Never_ci"][0])[0]
    else:
        min_k5 = min_never = None

    print("% ── tab:bypassk — generated by paper/gen-tables.py ──", file=out)
    print("\\begin{table}[t]", file=out)
    print("\\centering", file=out)
    print("\\caption{Bypass@K cumulative rates (\\%) under the \\emph{whitebox-no-feedback} (OSS-realistic) threat model across nine guardrail models, with 95\\% bootstrap CIs (1000 payload-level resamples) on the headline K=5 and K=20 columns. K=1 is the static payload; K$\\geq$2 uses attacker rewrites informed by Layer~1 rules and the Layer~2 prompt (white-box source disclosure) but receiving only ``REJECTED'' (no rejection-reason feedback). ``Never'' = fraction never bypassed within $K_{\\max}{=}20$. Attacker: Gemini~3.1~Pro~Preview (API). All values from complete runs at N=469. Sorted by Bypass@5 (ascending = more resilient).}", file=out)
    print("\\label{tab:bypassk}", file=out)
    print("\\small", file=out)
    print("\\setlength{\\tabcolsep}{2pt}", file=out)
    print("\\begin{tabular}{@{}lcccccccc@{}}", file=out)
    print("\\toprule", file=out)
    print("\\textbf{Guardrail Model} & \\textbf{K$\\leq$1} & \\textbf{K$\\leq$2} & \\textbf{K$\\leq$3} & \\textbf{K$\\leq$4} & \\textbf{K$\\leq$5 [95\\% CI]} & \\textbf{K$\\leq$10} & \\textbf{K$\\leq$20 [95\\% CI]} & \\textbf{Never [CI]} \\\\", file=out)
    print("\\midrule", file=out)
    for model, r in ordered:
        k5_pt, k5_lo, k5_hi = r["K=5_ci"]
        k20_pt, k20_lo, k20_hi = r["K=20_ci"]
        nv_pt, nv_lo, nv_hi = r["Never_ci"]
        k5_cell = f"\\textbf{{{k5_pt:.1f}}} [{k5_lo:.1f}, {k5_hi:.1f}]" if model == min_k5 else f"{k5_pt:.1f} [{k5_lo:.1f}, {k5_hi:.1f}]"
        nv_cell = f"\\textbf{{{nv_pt:.1f}}} [{nv_lo:.1f}, {nv_hi:.1f}]" if model == min_never else f"{nv_pt:.1f} [{nv_lo:.1f}, {nv_hi:.1f}]"
        print(
            f"{model} & "
            f"{r['K=1_point']:.1f} & "
            f"{r['K=2_point']:.1f} & "
            f"{r['K=3_point']:.1f} & "
            f"{r['K=4_point']:.1f} & "
            f"{k5_cell} & "
            f"{r['K=10_point']:.1f} & "
            f"{k20_pt:.1f} [{k20_lo:.1f}, {k20_hi:.1f}] & "
            f"{nv_cell} \\\\",
            file=out,
        )
    print("\\bottomrule", file=out)
    print("\\end{tabular}", file=out)
    print("", file=out)
    print("\\vspace{2pt}", file=out)
    print("{\\footnotesize CIs are payload-level percentile bootstrap (1000 resamples; seed=42, regenerated by \\texttt{paper/gen-tables.py}).}", file=out)
    print("\\end{table}", file=out)
    print("", file=out)
    return results


def emit_percategory_table(out=sys.stdout) -> dict:
    """Emit per-model per-category Bypass@5 table (PRIMARY-mode counterpart
    to tab:bypassk_cat). Returns the per-(model,category) point estimate dict.
    """
    # model -> cat -> point pct
    per_cat: dict[str, dict[str, float]] = {}
    for model, fname in PRIMARY_FILES.items():
        path = ADAPTIVE_DIR / fname
        if not path.exists():
            continue
        rows = load_rows(path)
        bucket: dict[str, list[int]] = defaultdict(list)
        for r in rows:
            cat = r.get("category", "?")
            byp = 1 if (r.get("bypass_at_k") is not None and r["bypass_at_k"] <= 5) else 0
            bucket[cat].append(byp)
        per_cat[model] = {
            cat: (sum(vals) / len(vals) * 100 if vals else 0.0)
            for cat, vals in bucket.items()
        }

    print("% ── tab:bypassk_cat (PRIMARY-mode) — generated by paper/gen-tables.py ──", file=out)
    print("\\begin{table}[t]", file=out)
    print("\\centering", file=out)
    print("\\caption{Per-category Bypass@5 rates (\\%) under the PRIMARY (whitebox-no-feedback) threat model across all nine models. Bold = lowest (most resilient) in each row. Attacker: Gemini~3.1~Pro~Preview. Generated by \\texttt{paper/gen-tables.py} from the released JSONL run files.}", file=out)
    print("\\label{tab:bypassk_cat_primary}", file=out)
    print("\\small", file=out)
    print("\\setlength{\\tabcolsep}{3pt}", file=out)
    print("\\begin{tabular}{@{}clccccccccc@{}}", file=out)
    print("\\toprule", file=out)
    header = "\\textbf{Cat} & & " + " & ".join(f"\\textbf{{{label}}}" for _, label in BYPASSK_CAT_COLS) + " \\\\"
    print(header, file=out)
    print("\\midrule", file=out)
    for cat, desc in CAT_DESCRIPTIONS:
        row_vals = []
        for model_key, _ in BYPASSK_CAT_COLS:
            v = per_cat.get(model_key, {}).get(cat)
            row_vals.append(v)
        # min for bolding (skip None)
        non_none = [v for v in row_vals if v is not None]
        min_v = min(non_none) if non_none else None
        cells = []
        for v in row_vals:
            if v is None:
                cells.append("--")
            elif min_v is not None and v == min_v:
                cells.append(f"\\textbf{{{v:.0f}}}")
            else:
                cells.append(f"{v:.0f}")
        print(f"{cat} & {desc} & " + " & ".join(cells) + " \\\\", file=out)
    print("\\bottomrule", file=out)
    print("\\end{tabular}", file=out)
    print("\\end{table}", file=out)
    print("", file=out)
    return per_cat


# ── CLI ────────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(
        description="Generate LaTeX source for paper headline tables from JSONL run files."
    )
    parser.add_argument(
        "--table",
        choices=["bypassk", "percategory", "all"],
        default="all",
        help="Which table to emit (default: all).",
    )
    parser.add_argument(
        "--output",
        default="-",
        help="Output file path or '-' for stdout (default: stdout).",
    )
    args = parser.parse_args()

    if not ADAPTIVE_DIR.exists():
        print(
            f"FATAL: adaptive runs directory not found: {ADAPTIVE_DIR}\n"
            f"  Set POP_PAY_NPM env var to the pop-pay-npm repo root.",
            file=sys.stderr,
        )
        sys.exit(2)

    out = sys.stdout if args.output == "-" else open(args.output, "w")
    try:
        print("% ──────────────────────────────────────────────────────────", file=out)
        print("% Auto-generated by paper/gen-tables.py — do not hand-edit.", file=out)
        print("% Regenerate with: python3 paper/gen-tables.py --table all", file=out)
        print("% Inputs: pop-pay-npm/tests/redteam/runs/adaptive/2026-04-28T19-50-* (PRIMARY)", file=out)
        print("% Bootstrap: 1000 payload-level resamples, seed=42.", file=out)
        print("% ──────────────────────────────────────────────────────────", file=out)
        print("", file=out)
        if args.table in ("bypassk", "all"):
            emit_bypassk_table(out)
        if args.table in ("percategory", "all"):
            emit_percategory_table(out)
    finally:
        if out is not sys.stdout:
            out.close()


if __name__ == "__main__":
    main()
