/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Derive AES-256 key from machine_id + username using scrypt.
 * Salt is reconstructed from XOR pairs, used, then zeroed.
 * Returns null if running from OSS source (no compiled salt data).
 */
export declare function deriveKey(machineId: Buffer, username: Buffer): Buffer | null
/** Return true if this is a hardened build with compiled salt data. */
export declare function isHardened(): boolean
